site_name: MIN Ontology
site_description: Documentation for the MIN foundational ontology
site_url: https://lepy.github.io/min-ontology/
repo_url: https://github.com/lepy/min-ontology
repo_name: lepy/min-ontology

docs_dir: docs
site_dir: site

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Foundations:
    - Model Overview: min-model.md
    - Class Catalog: class-catalog.md
    - Property Catalog: property-catalog.md
  - Guides:
    - Class Examples: examples.md
    - Breakfast Egg Tutorial (DE): breakfast_egg_de.md
    - Breakfast Egg Tutorial (EN): breakfast_egg_en.md
  - Reference:
    - Class Hierarchy (SVG): min_hierarchy.svg
    - Versioning: versioning.md
    - Changelog: changelog.md
    - Meta Vocabulary (DE): min-meta-vocabulary-de.md
    - Meta Vocabulary (EN): min-meta-vocabulary-en.md
  - Visualizations:
    - Visualization v1.0.0: min-v1_0_0-visualization.html
