PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {
  FILTER NOT EXISTS {
    ?p a owl:ObjectProperty .
    FILTER NOT EXISTS { ?p rdfs:domain ?domain . }
  }

  FILTER NOT EXISTS {
    ?p a owl:ObjectProperty .
    FILTER NOT EXISTS { ?p rdfs:range ?range . }
  }
}
