PREFIX min: <https://w3id.org/min#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE {
  min:EfficacyMode a owl:Class .
  {
    SELECT (COUNT(?mode) AS ?count)
    WHERE {
      min:EfficacyMode owl:oneOf ?list .
      ?list rdf:rest*/rdf:first ?mode .
    }
  }
  FILTER (?count = 10)
}
