PREFIX min: <https://w3id.org/min#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {
  min:materialProperty a owl:AnnotationProperty ; rdfs:label ?materialLabel .
  min:informationalProperty a owl:AnnotationProperty ; rdfs:label ?informationalLabel .
}
