PREFIX min: <https://w3id.org/min#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

ASK WHERE {
  min:originates a owl:ObjectProperty .
  min:originatedBy a owl:ObjectProperty .
  min:realizes a owl:ObjectProperty .
  min:realizedBy a owl:ObjectProperty .
  min:constrains a owl:ObjectProperty .
  min:governs a owl:ObjectProperty .
  min:formalizes a owl:ObjectProperty .
  min:evaluates a owl:ObjectProperty .
  min:concerns a owl:ObjectProperty .
  min:alternativeTo a owl:ObjectProperty .
  min:constitutes a owl:ObjectProperty .
  min:constitutedBy a owl:ObjectProperty .
  min:recognizes a owl:ObjectProperty .
  min:recognizedBy a owl:ObjectProperty .
  min:encodes a owl:ObjectProperty .
  min:encodedBy a owl:ObjectProperty .
  min:typifies a owl:ObjectProperty .
  min:typifiedBy a owl:ObjectProperty .
  min:comprises a owl:ObjectProperty .
  min:comprisedBy a owl:ObjectProperty .
  min:confirms a owl:ObjectProperty .
  min:confirmedBy a owl:ObjectProperty .
  min:refutes a owl:ObjectProperty .
  min:refutedBy a owl:ObjectProperty .
  min:entails a owl:ObjectProperty .
  min:supersedes a owl:ObjectProperty .
  min:supersededBy a owl:ObjectProperty .
  min:justifiedBy a owl:ObjectProperty .
  min:justifies a owl:ObjectProperty .
  min:holds a owl:ObjectProperty .
  min:heldBy a owl:ObjectProperty .
  min:about a owl:ObjectProperty .
  min:supportedBy a owl:ObjectProperty .
  min:supports a owl:ObjectProperty .
  min:underminedBy a owl:ObjectProperty .
  min:undermines a owl:ObjectProperty .
  min:hasEpistemicStatus a owl:ObjectProperty .
  min:hasConfidenceType a owl:ObjectProperty .
}
