PREFIX min: <https://w3id.org/min#>

# CQ01: Alle Hypothesen eines Agents
SELECT ?agent ?e ?gegenstand ?konfidenz WHERE {
  ?e a min:Epistemicum ;
     min:heldBy ?agent ;
     min:about ?gegenstand ;
     min:hasEpistemicStatus min:ES_Hypothetical ;
     min:hasConfidence ?konfidenz .
}
LIMIT 25
