PREFIX min: <https://w3id.org/min#>

# CQ07: Alle subjektiven Schaetzungen
SELECT ?e ?c WHERE {
  ?e a min:Epistemicum ;
     min:hasConfidenceType min:CT_Subjective ;
     min:hasConfidence ?c .
}
LIMIT 25
